definitions:
  api.HTTPResultMessage:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
info:
  contact:
    email: juergen.enge@unibas.ch
    name: Jürgen Enge
    url: https://ub.unibas.ch
  description: Mediaserver API for managing collections and items
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Mediaserver API
  version: "1.0"
paths:
  /collection/{collection}:
    get:
      description: retrieves mediaserver collection information
      operationId: get-collection-by-name
      parameters:
      - description: collection name
        in: path
        name: collection
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HTTPResultMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.HTTPResultMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.HTTPResultMessage'
      summary: gets collection data
      tags:
      - mediaserver
  /ping:
    get:
      description: for testing if server is running
      operationId: get-ping
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HTTPResultMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.HTTPResultMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.HTTPResultMessage'
      summary: does pong
      tags:
      - mediaserver
  /storage/{storageid}:
    get:
      description: retrieves mediaserver storage information
      operationId: get-storage-by-id
      parameters:
      - description: storage id
        in: path
        name: storageid
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HTTPResultMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.HTTPResultMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.HTTPResultMessage'
      summary: gets storage data
      tags:
      - mediaserver
swagger: "2.0"
